"""add validation_rules to attribute

Revision ID: 21aafc22dcd2
Revises: 66cd4a612e07
Create Date: 2026-07-12 06:02:16.653917

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "21aafc22dcd2"
down_revision: str | None = "66cd4a612e07"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attributes", sa.Column("validation_rules", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("attributes", "validation_rules")
    # ### end Alembic commands ###
