"""add_product_pieces_and_is_multi_piece

Revision ID: 37bb9f54b95a
Revises: 21aafc22dcd3
Create Date: 2026-07-15 08:34:43.504022

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "37bb9f54b95a"
down_revision: str | None = "21aafc22dcd3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_pieces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=True),
        sa.Column("name_ar", sa.String(length=255), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("color_option_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["color_option_id"],
            ["attribute_options.id"],
        ),
        sa.ForeignKeyConstraint(["product_id"], ["store_products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_pieces_product_id"), "product_pieces", ["product_id"], unique=False)
    op.add_column("store_products", sa.Column("is_multi_piece", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store_products", "is_multi_piece")
    op.drop_index(op.f("ix_product_pieces_product_id"), table_name="product_pieces")
    op.drop_table("product_pieces")
    # ### end Alembic commands ###
