"""add_source_url_to_store_products

Revision ID: 3ed8a36dd11e
Revises: 9d40219c5ac1
Create Date: 2026-07-17 02:48:23.380928

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3ed8a36dd11e"
down_revision: str | None = "9d40219c5ac1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("store_products", sa.Column("source_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store_products", "source_url")
    # ### end Alembic commands ###
