"""add product_variants and variant_attribute_options tables

Revision ID: 491b63edcb63
Revises: fdeb1468195f
Create Date: 2026-07-12 22:54:32.428794

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "491b63edcb63"
down_revision: str | None = "fdeb1468195f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_variants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("original_price", sa.Float(), nullable=True),
        sa.Column("sale_price", sa.Float(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["store_products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variant_attribute_options",
        sa.Column("variant_id", sa.String(length=36), nullable=False),
        sa.Column("attribute_option_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["attribute_option_id"], ["attribute_options.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["product_variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("variant_id", "attribute_option_id"),
    )
    op.add_column("product_images", sa.Column("variant_id", sa.String(length=36), nullable=True))
    op.create_foreign_key(None, "product_images", "product_variants", ["variant_id"], ["id"], ondelete="SET NULL")
    op.add_column("store_products", sa.Column("has_variants", sa.Boolean(), nullable=True, server_default=sa.text("false")))
    op.execute("UPDATE store_products SET has_variants = false WHERE has_variants IS NULL")
    op.alter_column("store_products", "has_variants", nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store_products", "has_variants")
    op.drop_constraint(None, "product_images", type_="foreignkey")
    op.drop_column("product_images", "variant_id")
    op.drop_table("variant_attribute_options")
    op.drop_table("product_variants")
    # ### end Alembic commands ###
