"""add_brands_table

Revision ID: 66cd4a612e07
Revises: ad3765c634ae
Create Date: 2026-07-11 23:48:24.378514

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "66cd4a612e07"
down_revision: str | None = "ad3765c634ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name_ar", sa.Text(), nullable=False),
        sa.Column("name_en", sa.Text(), nullable=False),
        sa.Column("name_fa", sa.Text(), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.alter_column("store_products", "brand", existing_type=sa.VARCHAR(length=255), type_=sa.String(length=36), existing_nullable=True)
    op.create_foreign_key(None, "store_products", "brands", ["brand"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "store_products", type_="foreignkey")
    op.alter_column("store_products", "brand", existing_type=sa.String(length=36), type_=sa.VARCHAR(length=255), existing_nullable=True)
    op.drop_table("brands")
    # ### end Alembic commands ###
