"""add_api_key_to_users

Revision ID: 7e5b2f872ef1
Revises: f2eef0aca076
Create Date: 2026-07-19 19:21:41.285004

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7e5b2f872ef1"
down_revision: str | None = "f2eef0aca076"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("api_key", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_users_api_key"), "users", ["api_key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_api_key"), table_name="users")
    op.drop_column("users", "api_key")
    # ### end Alembic commands ###
