"""Add collection_ar to store_products

Revision ID: 80b1fb555a0c
Revises: 7e5b2f872ef1
Create Date: 2026-07-20 13:55:09.025453

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "80b1fb555a0c"
down_revision: str | None = "7e5b2f872ef1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("store_products", sa.Column("collection_ar", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store_products", "collection_ar")
    # ### end Alembic commands ###
