"""add_color_sets_and_drop_piece_color

Revision ID: 9a37978dba36
Revises: 37bb9f54b95a
Create Date: 2026-07-15 09:13:00.885145

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9a37978dba36"
down_revision: str | None = "37bb9f54b95a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_color_sets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["store_products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_color_sets_product_id"), "product_color_sets", ["product_id"], unique=False)
    op.create_table(
        "product_color_set_values",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("color_set_id", sa.String(length=36), nullable=False),
        sa.Column("piece_id", sa.String(length=36), nullable=False),
        sa.Column("color_option_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["color_option_id"],
            ["attribute_options.id"],
        ),
        sa.ForeignKeyConstraint(["color_set_id"], ["product_color_sets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["piece_id"], ["product_pieces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("color_set_id", "piece_id", name="uq_color_set_piece"),
    )
    op.drop_constraint(op.f("product_pieces_color_option_id_fkey"), "product_pieces", type_="foreignkey")
    op.drop_column("product_pieces", "color_option_id")
    op.add_column("product_variants", sa.Column("color_set_id", sa.String(length=36), nullable=True))
    op.create_foreign_key(None, "product_variants", "product_color_sets", ["color_set_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product_variants", type_="foreignkey")
    op.drop_column("product_variants", "color_set_id")
    op.add_column("product_pieces", sa.Column("color_option_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("product_pieces_color_option_id_fkey"), "product_pieces", "attribute_options", ["color_option_id"], ["id"])
    op.drop_table("product_color_set_values")
    op.drop_index(op.f("ix_product_color_sets_product_id"), table_name="product_color_sets")
    op.drop_table("product_color_sets")
    # ### end Alembic commands ###
