"""add product definition system tables

Revision ID: 9d40219c5ac0
Revises: 70fc266ff398
Create Date: 2026-07-11 01:13:23.441797

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9d40219c5ac0"
down_revision: str | None = "70fc266ff398"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribute_groups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name_ar", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column("name_fa", sa.String(length=255), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "product_types",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name_ar", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column("name_fa", sa.String(length=255), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "attributes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("group_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name_ar", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column("name_fa", sa.String(length=255), nullable=False),
        sa.Column("description_ar", sa.Text(), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("description_fa", sa.Text(), nullable=True),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column("input_type", sa.String(length=30), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("is_filterable", sa.Boolean(), nullable=False),
        sa.Column("is_searchable", sa.Boolean(), nullable=False),
        sa.Column("is_visible_on_show", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["attribute_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_type_image_view_types",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_type_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name_ar", sa.Text(), nullable=False),
        sa.Column("name_en", sa.Text(), nullable=False),
        sa.Column("name_fa", sa.Text(), nullable=False),
        sa.Column("is_video", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attribute_options",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attribute_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("value_ar", sa.Text(), nullable=False),
        sa.Column("value_en", sa.Text(), nullable=False),
        sa.Column("value_fa", sa.Text(), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("color_hex", sa.String(length=7), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_type_attributes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_type_id", sa.String(length=36), nullable=False),
        sa.Column("attribute_id", sa.String(length=36), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "store_products",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("store_id", sa.String(length=36), nullable=False),
        sa.Column("product_type_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=True),
        sa.Column("name_ar", sa.Text(), nullable=True),
        sa.Column("name_en", sa.Text(), nullable=True),
        sa.Column("name_fa", sa.Text(), nullable=True),
        sa.Column("short_description_ar", sa.Text(), nullable=True),
        sa.Column("short_description_en", sa.Text(), nullable=True),
        sa.Column("short_description_fa", sa.Text(), nullable=True),
        sa.Column("long_description_ar", sa.Text(), nullable=True),
        sa.Column("long_description_en", sa.Text(), nullable=True),
        sa.Column("long_description_fa", sa.Text(), nullable=True),
        sa.Column("ai_description_ar", sa.Text(), nullable=True),
        sa.Column("ai_description_en", sa.Text(), nullable=True),
        sa.Column("ai_description_fa", sa.Text(), nullable=True),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("original_price", sa.Float(), nullable=True),
        sa.Column("sale_price", sa.Float(), nullable=True),
        sa.Column("sale_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sale_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("weight_unit", sa.String(length=10), nullable=False),
        sa.Column("collection", sa.String(length=255), nullable=True),
        sa.Column("visibility_regions", sa.JSON(), nullable=True),
        sa.Column("country_of_origin", sa.String(length=100), nullable=True),
        sa.Column("care_instructions_ar", sa.Text(), nullable=True),
        sa.Column("care_instructions_en", sa.Text(), nullable=True),
        sa.Column("care_instructions_fa", sa.Text(), nullable=True),
        sa.Column("model_height", sa.String(length=50), nullable=True),
        sa.Column("model_wears_size", sa.String(length=20), nullable=True),
        sa.Column("video_url", sa.Text(), nullable=True),
        sa.Column("meta_title_ar", sa.Text(), nullable=True),
        sa.Column("meta_title_en", sa.Text(), nullable=True),
        sa.Column("meta_title_fa", sa.Text(), nullable=True),
        sa.Column("meta_description_ar", sa.Text(), nullable=True),
        sa.Column("meta_description_en", sa.Text(), nullable=True),
        sa.Column("meta_description_fa", sa.Text(), nullable=True),
        sa.Column("ai_search_boost", sa.Text(), nullable=True),
        sa.Column("embedding_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "product_attribute_values",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("attribute_id", sa.String(length=36), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attributes.id"],
        ),
        sa.ForeignKeyConstraint(["product_id"], ["store_products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("view_type_id", sa.String(length=36), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("alt_text_ar", sa.Text(), nullable=True),
        sa.Column("alt_text_en", sa.Text(), nullable=True),
        sa.Column("alt_text_fa", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_video", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["store_products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["view_type_id"],
            ["product_type_image_view_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_outfits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("matches_product_id", sa.String(length=36), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["matches_product_id"],
            ["store_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["store_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_sizes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("size_label", sa.String(length=50), nullable=False),
        sa.Column("size_system", sa.String(length=20), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["store_products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("categories", sa.Column("parent_id", sa.String(length=36), nullable=True))
    op.add_column("categories", sa.Column("product_type_id", sa.String(length=36), nullable=True))
    op.add_column("categories", sa.Column("icon", sa.String(length=100), nullable=True))
    op.add_column("categories", sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False))
    op.create_foreign_key(None, "categories", "categories", ["parent_id"], ["id"])
    op.create_foreign_key(None, "categories", "product_types", ["product_type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_column("categories", "sort_order")
    op.drop_column("categories", "icon")
    op.drop_column("categories", "product_type_id")
    op.drop_column("categories", "parent_id")
    op.drop_table("product_sizes")
    op.drop_table("product_outfits")
    op.drop_table("product_images")
    op.drop_table("product_attribute_values")
    op.drop_table("store_products")
    op.drop_table("product_type_attributes")
    op.drop_table("attribute_options")
    op.drop_table("product_type_image_view_types")
    op.drop_table("attributes")
    op.drop_table("product_types")
    op.drop_table("attribute_groups")
    # ### end Alembic commands ###
