"""add scrape_products table

Revision ID: a1e7d878bdb8
Revises: aafe2d25aa13
Create Date: 2026-07-14 09:49:47.929521

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a1e7d878bdb8"
down_revision: str | None = "aafe2d25aa13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scrape_products",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_category", sa.String(length=500), nullable=True),
        sa.Column("country", sa.String(length=5), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("raw_data", sa.JSON(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_id", "country", name="uq_scrape_product_source"),
    )
    op.create_index(op.f("ix_scrape_products_source"), "scrape_products", ["source"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scrape_products_source"), table_name="scrape_products")
    op.drop_table("scrape_products")
    # ### end Alembic commands ###
