"""Add is_search_affecting flag to attributes.

Revision ID: a7f3e1d9c2b4
Revises: c1f2e3d4a5b6
Create Date: 2026-08-12

Data seed: marks search-affecting attributes (style discriminators) as True so
embedding text includes only those. Flags are the canonical mapping mirrored
from scripts/seed_data/search_affecting_flags.json.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a7f3e1d9c2b4"
down_revision: str | None = "c1f2e3d4a5b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TRUE_CODES: list[str] = [
    "abaya_closure_type",
    "abaya_length",
    "abaya_neckline",
    "abaya_sleeve_style",
    "abaya_style",
    "activewear_fit_type",
    "activewear_sleeve_style",
    "activity",
    "applicator_type",
    "arch_support_type",
    "back_design",
    "bag_closure_type",
    "bag_lining_material",
    "bag_shape",
    "bag_type",
    "base_notes",
    "beauty_formulation",
    "beauty_fragrance_family",
    "beauty_product_type",
    "beauty_skin_type",
    "belt_closure_type",
    "body_care_formulation",
    "body_care_skin_type",
    "body_jewelry_type",
    "bodycare_type",
    "boot_heel_height",
    "boot_season",
    "boot_shaft_height",
    "boot_toe_style",
    "bottom_closure_type",
    "bottom_fit_type",
    "bra_closure_type",
    "bra_style",
    "bra_support_level",
    "bracelet_clasp_type",
    "bracelet_design",
    "brim_style",
    "case_material",
    "case_shape",
    "chain_type",
    "clasp_type",
    "closure_type",
    "concentration",
    "coverage",
    "coverage_level",
    "cushioning_level",
    "dial_color",
    "dress_skirt_length",
    "dress_style",
    "earring_closure",
    "earring_design",
    "embellishment_type",
    "eyewear_frame_shape",
    "fabric_type",
    "finish",
    "fit_type",
    "footwear_subtype",
    "fragrance_family",
    "fragrance_type",
    "frame_material",
    "frame_shape",
    "gemstone_type",
    "glove_type",
    "hair_accessory_type",
    "hair_type",
    "hardware_color",
    "heart_notes",
    "heel_height",
    "heel_occasion",
    "heel_toe_style",
    "heel_type",
    "heel_type_boots",
    "hood_type",
    "insulation_type",
    "jacket_length",
    "jewelry_style",
    "keychain_type",
    "lapel_style",
    "lens_color",
    "lens_material",
    "lingerie_neckline",
    "lingerie_sleeve_style",
    "lining_type",
    "longevity",
    "main_material",
    "material_headwear",
    "material_leather_goods",
    "material_specialty",
    "material_textile",
    "metal_purity",
    "metal_type",
    "modesty_level",
    "movement_type",
    "necklace_design",
    "necklace_length",
    "neckline",
    "occasion",
    "opacity_level",
    "other_jewelry_clasp_type",
    "outer_material",
    "outerwear_closure_type",
    "outerwear_fit_type",
    "outerwear_length",
    "outerwear_neckline",
    "outerwear_sleeve_style",
    "pants_length",
    "pattern",
    "phone_case_type",
    "pin_backing_type",
    "pin_closure",
    "plating",
    "pocket_style",
    "primary_color",
    "ring_design",
    "robe_style",
    "sandal_heel_height",
    "sandal_heel_type",
    "sandal_occasion",
    "sandal_toe_style",
    "scarf_fabric_type",
    "scarf_length",
    "scarf_shape",
    "scarf_type",
    "scent_note",
    "season",
    "setting_style",
    "shade_name",
    "shoe_closure_type",
    "shoe_lining_material",
    "sillage",
    "skirt_closure_type",
    "skirt_fit_type",
    "skirt_length",
    "skirt_silhouette",
    "skirt_waist_rise",
    "skirt_waistband_style",
    "sleepwear_type",
    "sleeve_style",
    "sole_material",
    "spf",
    "sports_type",
    "stone_creation_method",
    "stone_cut",
    "stone_setting_type",
    "stone_shape",
    "strap_material",
    "strap_type",
    "style",
    "suit_fit_type",
    "suit_lining_type",
    "suit_type",
    "swimsuit_type",
    "swimwear_sleeve_style",
    "target_customer",
    "textile_lining_material",
    "textile_season",
    "tie_closure",
    "tie_fabric",
    "tie_length",
    "top_closure_type",
    "top_fit_type",
    "top_length",
    "top_neckline",
    "top_notes",
    "top_sleeve_style",
    "trouser_fit",
    "undertone",
    "underwear_style",
    "upper_material_athletic",
    "upper_material_boots",
    "upper_material_heels",
    "upper_material_sandals",
    "vent_style",
    "waist_rise",
    "waistband_style",
    "wallet_type",
    "watch_movement_type",
    "watch_style",
]


def upgrade() -> None:
    op.add_column(
        "attributes",
        sa.Column("is_search_affecting", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    if TRUE_CODES:
        placeholders = ", ".join(f":code{i}" for i in range(len(TRUE_CODES)))
        params = {}
        for i, c in enumerate(TRUE_CODES):
            params[f"code{i}"] = c
        op.execute(sa.text(f"UPDATE attributes SET is_search_affecting = true WHERE code IN ({placeholders})").bindparams(**params))


def downgrade() -> None:
    op.drop_column("attributes", "is_search_affecting")
