"""add_color_family_and_is_major

Revision ID: ad3765c634ae
Revises: 9d40219c5ac0
Create Date: 2026-07-11 23:12:28.026434

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ad3765c634ae"
down_revision: str | None = "9d40219c5ac0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("attribute_options", sa.Column("color_family", sa.String(length=50), nullable=True))
    op.add_column("attribute_options", sa.Column("is_major", sa.Boolean(), nullable=True))
    op.execute("UPDATE attribute_options SET is_major = false WHERE is_major IS NULL")
    op.alter_column("attribute_options", "is_major", nullable=False)
    op.alter_column("store_products", "visibility_regions", existing_type=postgresql.JSONB(astext_type=sa.Text()), type_=sa.JSON(), existing_nullable=True)
    # ### end alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("store_products", "visibility_regions", existing_type=sa.JSON(), type_=postgresql.JSONB(astext_type=sa.Text()), existing_nullable=True)
    op.drop_column("attribute_options", "is_major")
    op.drop_column("attribute_options", "color_family")
    # ### end alembic commands ###
