"""add prompt_templates table

Revision ID: d77bcf27b2ca
Revises: 7f3777bdd0fc
Create Date: 2026-07-22 02:43:19.995053

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d77bcf27b2ca"
down_revision: str | None = "7f3777bdd0fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_templates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompt_templates_is_active"), "prompt_templates", ["is_active"], unique=False)
    op.create_index(op.f("ix_prompt_templates_type"), "prompt_templates", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_templates_type"), table_name="prompt_templates")
    op.drop_index(op.f("ix_prompt_templates_is_active"), table_name="prompt_templates")
    op.drop_table("prompt_templates")
    # ### end Alembic commands ###
