"""Add unique constraint store_id+source_url on store_products

Revision ID: deb0711c36d2
Revises: 3ed8a36dd11e
Create Date: 2026-07-19 04:06:33.796977

"""

from collections.abc import Sequence

from alembic import op

revision: str = "deb0711c36d2"
down_revision: str | None = "3ed8a36dd11e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_store_product_source", "store_products", ["store_id", "source_url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_store_product_source", "store_products", type_="unique")
    # ### end Alembic commands ###
