"""add_images_cached_to_scrape_products

Revision ID: f2eef0aca076
Revises: deb0711c36d2
Create Date: 2026-07-19 17:23:15.697509

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f2eef0aca076"
down_revision: str | None = "deb0711c36d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scrape_products", sa.Column("images_cached", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scrape_products", "images_cached")
    # ### end Alembic commands ###
