export interface Country {
  code: string;
  name: string;
  nameAr: string;
  nameFa: string;
  dialCode: string;
  flag: string;
}

export const countries: Country[] = [
  {
    code: 'KW',
    name: 'Kuwait',
    nameAr: 'الكويت',
    nameFa: 'کویت',
    dialCode: '+965',
    flag: '🇰🇼',
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    nameAr: 'الإمارات العربية المتحدة',
    nameFa: 'امارات متحده عربی',
    dialCode: '+971',
    flag: '🇦🇪',
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    nameAr: 'المملكة العربية السعودية',
    nameFa: 'عربستان سعودی',
    dialCode: '+966',
    flag: '🇸🇦',
  },
  {
    code: 'QA',
    name: 'Qatar',
    nameAr: 'قطر',
    nameFa: 'قطر',
    dialCode: '+974',
    flag: '🇶🇦',
  },
  {
    code: 'BH',
    name: 'Bahrain',
    nameAr: 'البحرين',
    nameFa: 'بحرین',
    dialCode: '+973',
    flag: '🇧🇭',
  },
  {
    code: 'OM',
    name: 'Oman',
    nameAr: 'عمان',
    nameFa: 'عمان',
    dialCode: '+968',
    flag: '🇴🇲',
  },
  {
    code: 'IQ',
    name: 'Iraq',
    nameAr: 'العراق',
    nameFa: 'عراق',
    dialCode: '+964',
    flag: '🇮🇶',
  },
  {
    code: 'JO',
    name: 'Jordan',
    nameAr: 'الأردن',
    nameFa: 'اردن',
    dialCode: '+962',
    flag: '🇯🇴',
  },
  {
    code: 'LB',
    name: 'Lebanon',
    nameAr: 'لبنان',
    nameFa: 'لبنان',
    dialCode: '+961',
    flag: '🇱🇧',
  },
  {
    code: 'SY',
    name: 'Syria',
    nameAr: 'سوريا',
    nameFa: 'سوریه',
    dialCode: '+963',
    flag: '🇸🇾',
  },
  {
    code: 'YE',
    name: 'Yemen',
    nameAr: 'اليمن',
    nameFa: 'یمن',
    dialCode: '+967',
    flag: '🇾🇪',
  },
  {
    code: 'PS',
    name: 'Palestine',
    nameAr: 'فلسطين',
    nameFa: 'فلسطین',
    dialCode: '+970',
    flag: '🇵🇸',
  },
  {
    code: 'EG',
    name: 'Egypt',
    nameAr: 'مصر',
    nameFa: 'مصر',
    dialCode: '+20',
    flag: '🇪🇬',
  },
  {
    code: 'SD',
    name: 'Sudan',
    nameAr: 'السودان',
    nameFa: 'سودان',
    dialCode: '+249',
    flag: '🇸🇩',
  },
  {
    code: 'LY',
    name: 'Libya',
    nameAr: 'ليبيا',
    nameFa: 'لیبی',
    dialCode: '+218',
    flag: '🇱🇾',
  },
  {
    code: 'TN',
    name: 'Tunisia',
    nameAr: 'تونس',
    nameFa: 'تونس',
    dialCode: '+216',
    flag: '🇹🇳',
  },
  {
    code: 'DZ',
    name: 'Algeria',
    nameAr: 'الجزائر',
    nameFa: 'الجزایر',
    dialCode: '+213',
    flag: '🇩🇿',
  },
  {
    code: 'MA',
    name: 'Morocco',
    nameAr: 'المغرب',
    nameFa: 'مراکش',
    dialCode: '+212',
    flag: '🇲🇦',
  },
  {
    code: 'MR',
    name: 'Mauritania',
    nameAr: 'موريتانيا',
    nameFa: 'موریتانی',
    dialCode: '+222',
    flag: '🇲🇷',
  },
  {
    code: 'SO',
    name: 'Somalia',
    nameAr: 'الصومال',
    nameFa: 'سومالی',
    dialCode: '+252',
    flag: '🇸🇴',
  },
  {
    code: 'DJ',
    name: 'Djibouti',
    nameAr: 'جيبوتي',
    nameFa: 'جیبوتی',
    dialCode: '+253',
    flag: '🇩🇯',
  },
  {
    code: 'KM',
    name: 'Comoros',
    nameAr: 'جزر القمر',
    nameFa: 'کومور',
    dialCode: '+269',
    flag: '🇰🇲',
  },
  {
    code: 'IR',
    name: 'Iran',
    nameAr: 'إيران',
    nameFa: 'ایران',
    dialCode: '+98',
    flag: '🇮🇷',
  },
  {
    code: 'TR',
    name: 'Turkey',
    nameAr: 'تركيا',
    nameFa: 'ترکیه',
    dialCode: '+90',
    flag: '🇹🇷',
  },
  {
    code: 'AF',
    name: 'Afghanistan',
    nameAr: 'أفغانستان',
    nameFa: 'افغانستان',
    dialCode: '+93',
    flag: '🇦🇫',
  },
  {
    code: 'PK',
    name: 'Pakistan',
    nameAr: 'باكستان',
    nameFa: 'پاکستان',
    dialCode: '+92',
    flag: '🇵🇰',
  },
  {
    code: 'IN',
    name: 'India',
    nameAr: 'الهند',
    nameFa: 'هند',
    dialCode: '+91',
    flag: '🇮🇳',
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    nameAr: 'بنغلاديش',
    nameFa: 'بنگلادش',
    dialCode: '+880',
    flag: '🇧🇩',
  },
  {
    code: 'LK',
    name: 'Sri Lanka',
    nameAr: 'سريلانكا',
    nameFa: 'سری‌لانکا',
    dialCode: '+94',
    flag: '🇱🇰',
  },
  {
    code: 'NP',
    name: 'Nepal',
    nameAr: 'نيبال',
    nameFa: 'نپال',
    dialCode: '+977',
    flag: '🇳🇵',
  },
  {
    code: 'BT',
    name: 'Bhutan',
    nameAr: 'بوتان',
    nameFa: 'بوتان',
    dialCode: '+975',
    flag: '🇧🇹',
  },
  {
    code: 'MV',
    name: 'Maldives',
    nameAr: 'جزر المالديف',
    nameFa: 'مالدیو',
    dialCode: '+960',
    flag: '🇲🇻',
  },
  {
    code: 'CN',
    name: 'China',
    nameAr: 'الصين',
    nameFa: 'چین',
    dialCode: '+86',
    flag: '🇨🇳',
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    nameAr: 'هونغ كونغ',
    nameFa: 'هنگ‌کنگ',
    dialCode: '+852',
    flag: '🇭🇰',
  },
  {
    code: 'TW',
    name: 'Taiwan',
    nameAr: 'تايوان',
    nameFa: 'تایوان',
    dialCode: '+886',
    flag: '🇹🇼',
  },
  {
    code: 'JP',
    name: 'Japan',
    nameAr: 'اليابان',
    nameFa: 'ژاپن',
    dialCode: '+81',
    flag: '🇯🇵',
  },
  {
    code: 'KR',
    name: 'South Korea',
    nameAr: 'كوريا الجنوبية',
    nameFa: 'کره جنوبی',
    dialCode: '+82',
    flag: '🇰🇷',
  },
  {
    code: 'KP',
    name: 'North Korea',
    nameAr: 'كوريا الشمالية',
    nameFa: 'کره شمالی',
    dialCode: '+850',
    flag: '🇰🇵',
  },
  {
    code: 'MN',
    name: 'Mongolia',
    nameAr: 'منغوليا',
    nameFa: 'مغولستان',
    dialCode: '+976',
    flag: '🇲🇳',
  },
  {
    code: 'TH',
    name: 'Thailand',
    nameAr: 'تايلاند',
    nameFa: 'تایلند',
    dialCode: '+66',
    flag: '🇹🇭',
  },
  {
    code: 'VN',
    name: 'Vietnam',
    nameAr: 'فيتنام',
    nameFa: 'ویتنام',
    dialCode: '+84',
    flag: '🇻🇳',
  },
  {
    code: 'KH',
    name: 'Cambodia',
    nameAr: 'كمبوديا',
    nameFa: 'کامبوج',
    dialCode: '+855',
    flag: '🇰🇭',
  },
  {
    code: 'LA',
    name: 'Laos',
    nameAr: 'لاوس',
    nameFa: 'لائوس',
    dialCode: '+856',
    flag: '🇱🇦',
  },
  {
    code: 'MM',
    name: 'Myanmar',
    nameAr: 'ميانمار',
    nameFa: 'میانمار',
    dialCode: '+95',
    flag: '🇲🇲',
  },
  {
    code: 'MY',
    name: 'Malaysia',
    nameAr: 'ماليزيا',
    nameFa: 'مالزی',
    dialCode: '+60',
    flag: '🇲🇾',
  },
  {
    code: 'SG',
    name: 'Singapore',
    nameAr: 'سنغافورة',
    nameFa: 'سنگاپور',
    dialCode: '+65',
    flag: '🇸🇬',
  },
  {
    code: 'PH',
    name: 'Philippines',
    nameAr: 'الفلبين',
    nameFa: 'فیلیپین',
    dialCode: '+63',
    flag: '🇵🇭',
  },
  {
    code: 'ID',
    name: 'Indonesia',
    nameAr: 'إندونيسيا',
    nameFa: 'اندونزی',
    dialCode: '+62',
    flag: '🇮🇩',
  },
  {
    code: 'TL',
    name: 'Timor-Leste',
    nameAr: 'تيمور الشرقية',
    nameFa: 'تیمور شرقی',
    dialCode: '+670',
    flag: '🇹🇱',
  },
  {
    code: 'US',
    name: 'United States',
    nameAr: 'الولايات المتحدة',
    nameFa: 'ایالات متحده',
    dialCode: '+1',
    flag: '🇺🇸',
  },
  {
    code: 'CA',
    name: 'Canada',
    nameAr: 'كندا',
    nameFa: 'کانادا',
    dialCode: '+1',
    flag: '🇨🇦',
  },
  {
    code: 'MX',
    name: 'Mexico',
    nameAr: 'المكسيك',
    nameFa: 'مکزیک',
    dialCode: '+52',
    flag: '🇲🇽',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    nameAr: 'المملكة المتحدة',
    nameFa: 'بریتانیا',
    dialCode: '+44',
    flag: '🇬🇧',
  },
  {
    code: 'IE',
    name: 'Ireland',
    nameAr: 'أيرلندا',
    nameFa: 'ایرلند',
    dialCode: '+353',
    flag: '🇮🇪',
  },
  {
    code: 'FR',
    name: 'France',
    nameAr: 'فرنسا',
    nameFa: 'فرانسه',
    dialCode: '+33',
    flag: '🇫🇷',
  },
  {
    code: 'DE',
    name: 'Germany',
    nameAr: 'ألمانيا',
    nameFa: 'آلمان',
    dialCode: '+49',
    flag: '🇩🇪',
  },
  {
    code: 'IT',
    name: 'Italy',
    nameAr: 'إيطاليا',
    nameFa: 'ایتالیا',
    dialCode: '+39',
    flag: '🇮🇹',
  },
  {
    code: 'ES',
    name: 'Spain',
    nameAr: 'إسبانيا',
    nameFa: 'اسپانیا',
    dialCode: '+34',
    flag: '🇪🇸',
  },
  {
    code: 'PT',
    name: 'Portugal',
    nameAr: 'البرتغال',
    nameFa: 'پرتغال',
    dialCode: '+351',
    flag: '🇵🇹',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    nameAr: 'هولندا',
    nameFa: 'هلند',
    dialCode: '+31',
    flag: '🇳🇱',
  },
  {
    code: 'BE',
    name: 'Belgium',
    nameAr: 'بلجيكا',
    nameFa: 'بلژیک',
    dialCode: '+32',
    flag: '🇧🇪',
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    nameAr: 'لوكسمبورغ',
    nameFa: 'لوکزامبورگ',
    dialCode: '+352',
    flag: '🇱🇺',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    nameAr: 'سويسرا',
    nameFa: 'سوئیس',
    dialCode: '+41',
    flag: '🇨🇭',
  },
  {
    code: 'AT',
    name: 'Austria',
    nameAr: 'النمسا',
    nameFa: 'اتریش',
    dialCode: '+43',
    flag: '🇦🇹',
  },
  {
    code: 'DK',
    name: 'Denmark',
    nameAr: 'الدنمارك',
    nameFa: 'دانمارک',
    dialCode: '+45',
    flag: '🇩🇰',
  },
  {
    code: 'SE',
    name: 'Sweden',
    nameAr: 'السويد',
    nameFa: 'سوئد',
    dialCode: '+46',
    flag: '🇸🇪',
  },
  {
    code: 'NO',
    name: 'Norway',
    nameAr: 'النرويج',
    nameFa: 'نروژ',
    dialCode: '+47',
    flag: '🇳🇴',
  },
  {
    code: 'FI',
    name: 'Finland',
    nameAr: 'فنلندا',
    nameFa: 'فنلاند',
    dialCode: '+358',
    flag: '🇫🇮',
  },
  {
    code: 'IS',
    name: 'Iceland',
    nameAr: 'آيسلندا',
    nameFa: 'ایسلند',
    dialCode: '+354',
    flag: '🇮🇸',
  },
  {
    code: 'EE',
    name: 'Estonia',
    nameAr: 'إستونيا',
    nameFa: 'استونی',
    dialCode: '+372',
    flag: '🇪🇪',
  },
  {
    code: 'LV',
    name: 'Latvia',
    nameAr: 'لاتفيا',
    nameFa: 'لتونی',
    dialCode: '+371',
    flag: '🇱🇻',
  },
  {
    code: 'LT',
    name: 'Lithuania',
    nameAr: 'ليتوانيا',
    nameFa: 'لیتوانی',
    dialCode: '+370',
    flag: '🇱🇹',
  },
  {
    code: 'PL',
    name: 'Poland',
    nameAr: 'بولندا',
    nameFa: 'لهستان',
    dialCode: '+48',
    flag: '🇵🇱',
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    nameAr: 'جمهورية التشيك',
    nameFa: 'جمهوری چک',
    dialCode: '+420',
    flag: '🇨🇿',
  },
  {
    code: 'SK',
    name: 'Slovakia',
    nameAr: 'سلوفاكيا',
    nameFa: 'اسلواکی',
    dialCode: '+421',
    flag: '🇸🇰',
  },
  {
    code: 'HU',
    name: 'Hungary',
    nameAr: 'المجر',
    nameFa: 'مجارستان',
    dialCode: '+36',
    flag: '🇭🇺',
  },
  {
    code: 'RO',
    name: 'Romania',
    nameAr: 'رومانيا',
    nameFa: 'رومانی',
    dialCode: '+40',
    flag: '🇷🇴',
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    nameAr: 'بلغاريا',
    nameFa: 'بلغارستان',
    dialCode: '+359',
    flag: '🇧🇬',
  },
  {
    code: 'GR',
    name: 'Greece',
    nameAr: 'اليونان',
    nameFa: 'یونان',
    dialCode: '+30',
    flag: '🇬🇷',
  },
  {
    code: 'CY',
    name: 'Cyprus',
    nameAr: 'قبرص',
    nameFa: 'قبرس',
    dialCode: '+357',
    flag: '🇨🇾',
  },
  {
    code: 'MT',
    name: 'Malta',
    nameAr: 'مالطا',
    nameFa: 'مالت',
    dialCode: '+356',
    flag: '🇲🇹',
  },
  {
    code: 'AL',
    name: 'Albania',
    nameAr: 'ألبانيا',
    nameFa: 'آلبانی',
    dialCode: '+355',
    flag: '🇦🇱',
  },
  {
    code: 'MK',
    name: 'North Macedonia',
    nameAr: 'مقدونيا الشمالية',
    nameFa: 'مقدونیه شمالی',
    dialCode: '+389',
    flag: '🇲🇰',
  },
  {
    code: 'RS',
    name: 'Serbia',
    nameAr: 'صربيا',
    nameFa: 'صربستان',
    dialCode: '+381',
    flag: '🇷🇸',
  },
  {
    code: 'ME',
    name: 'Montenegro',
    nameAr: 'الجبل الأسود',
    nameFa: 'مونته‌نگرو',
    dialCode: '+382',
    flag: '🇲🇪',
  },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    nameAr: 'البوسنة والهرسك',
    nameFa: 'بوسنی و هرزگوین',
    dialCode: '+387',
    flag: '🇧🇦',
  },
  {
    code: 'HR',
    name: 'Croatia',
    nameAr: 'كرواتيا',
    nameFa: 'کرواسی',
    dialCode: '+385',
    flag: '🇭🇷',
  },
  {
    code: 'SI',
    name: 'Slovenia',
    nameAr: 'سلوفينيا',
    nameFa: 'اسلوونی',
    dialCode: '+386',
    flag: '🇸🇮',
  },
  {
    code: 'XK',
    name: 'Kosovo',
    nameAr: 'كوسوفو',
    nameFa: 'کوزوو',
    dialCode: '+383',
    flag: '🇽🇰',
  },
  {
    code: 'RU',
    name: 'Russia',
    nameAr: 'روسيا',
    nameFa: 'روسیه',
    dialCode: '+7',
    flag: '🇷🇺',
  },
  {
    code: 'UA',
    name: 'Ukraine',
    nameAr: 'أوكرانيا',
    nameFa: 'اوکراین',
    dialCode: '+380',
    flag: '🇺🇦',
  },
  {
    code: 'BY',
    name: 'Belarus',
    nameAr: 'بيلاروسيا',
    nameFa: 'بلاروس',
    dialCode: '+375',
    flag: '🇧🇾',
  },
  {
    code: 'MD',
    name: 'Moldova',
    nameAr: 'مولدوفا',
    nameFa: 'مولداوی',
    dialCode: '+373',
    flag: '🇲🇩',
  },
  {
    code: 'GE',
    name: 'Georgia',
    nameAr: 'جورجيا',
    nameFa: 'گرجستان',
    dialCode: '+995',
    flag: '🇬🇪',
  },
  {
    code: 'AM',
    name: 'Armenia',
    nameAr: 'أرمينيا',
    nameFa: 'ارمنستان',
    dialCode: '+374',
    flag: '🇦🇲',
  },
  {
    code: 'AZ',
    name: 'Azerbaijan',
    nameAr: 'أذربيجان',
    nameFa: 'آذربایجان',
    dialCode: '+994',
    flag: '🇦🇿',
  },
  {
    code: 'KZ',
    name: 'Kazakhstan',
    nameAr: 'كازاخستان',
    nameFa: 'قزاقستان',
    dialCode: '+7',
    flag: '🇰🇿',
  },
  {
    code: 'UZ',
    name: 'Uzbekistan',
    nameAr: 'أوزبكستان',
    nameFa: 'ازبکستان',
    dialCode: '+998',
    flag: '🇺🇿',
  },
  {
    code: 'TM',
    name: 'Turkmenistan',
    nameAr: 'تركمانستان',
    nameFa: 'ترکمنستان',
    dialCode: '+993',
    flag: '🇹🇲',
  },
  {
    code: 'KG',
    name: 'Kyrgyzstan',
    nameAr: 'قيرغيزستان',
    nameFa: 'قرقیزستان',
    dialCode: '+996',
    flag: '🇰🇬',
  },
  {
    code: 'TJ',
    name: 'Tajikistan',
    nameAr: 'طاجيكستان',
    nameFa: 'تاجیکستان',
    dialCode: '+992',
    flag: '🇹🇯',
  },
  {
    code: 'AU',
    name: 'Australia',
    nameAr: 'أستراليا',
    nameFa: 'استرالیا',
    dialCode: '+61',
    flag: '🇦🇺',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    nameAr: 'نيوزيلندا',
    nameFa: 'نیوزیلند',
    dialCode: '+64',
    flag: '🇳🇿',
  },
  {
    code: 'ZA',
    name: 'South Africa',
    nameAr: 'جنوب أفريقيا',
    nameFa: 'آفریقای جنوبی',
    dialCode: '+27',
    flag: '🇿🇦',
  },
  {
    code: 'NG',
    name: 'Nigeria',
    nameAr: 'نيجيريا',
    nameFa: 'نیجریه',
    dialCode: '+234',
    flag: '🇳🇬',
  },
  {
    code: 'KE',
    name: 'Kenya',
    nameAr: 'كينيا',
    nameFa: 'کنیا',
    dialCode: '+254',
    flag: '🇰🇪',
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    nameAr: 'إثيوبيا',
    nameFa: 'اتیوپی',
    dialCode: '+251',
    flag: '🇪🇹',
  },
  {
    code: 'GH',
    name: 'Ghana',
    nameAr: 'غانا',
    nameFa: 'غنا',
    dialCode: '+233',
    flag: '🇬🇭',
  },
  {
    code: 'CM',
    name: 'Cameroon',
    nameAr: 'الكاميرون',
    nameFa: 'کامرون',
    dialCode: '+237',
    flag: '🇨🇲',
  },
  {
    code: 'CI',
    name: 'Ivory Coast',
    nameAr: 'ساحل العاج',
    nameFa: 'ساحل عاج',
    dialCode: '+225',
    flag: '🇨🇮',
  },
  {
    code: 'SN',
    name: 'Senegal',
    nameAr: 'السنغال',
    nameFa: 'سنگال',
    dialCode: '+221',
    flag: '🇸🇳',
  },
  {
    code: 'ML',
    name: 'Mali',
    nameAr: 'مالي',
    nameFa: 'مالی',
    dialCode: '+223',
    flag: '🇲🇱',
  },
  {
    code: 'UG',
    name: 'Uganda',
    nameAr: 'أوغندا',
    nameFa: 'اوگاندا',
    dialCode: '+256',
    flag: '🇺🇬',
  },
  {
    code: 'TZ',
    name: 'Tanzania',
    nameAr: 'تنزانيا',
    nameFa: 'تانزانیا',
    dialCode: '+255',
    flag: '🇹🇿',
  },
  {
    code: 'ZM',
    name: 'Zambia',
    nameAr: 'زامبيا',
    nameFa: 'زامبیا',
    dialCode: '+260',
    flag: '🇿🇲',
  },
  {
    code: 'ZW',
    name: 'Zimbabwe',
    nameAr: 'زيمبابوي',
    nameFa: 'زیمبابوه',
    dialCode: '+263',
    flag: '🇿🇼',
  },
  {
    code: 'MZ',
    name: 'Mozambique',
    nameAr: 'موزمبيق',
    nameFa: 'موزامبیک',
    dialCode: '+258',
    flag: '🇲🇿',
  },
  {
    code: 'AO',
    name: 'Angola',
    nameAr: 'أنغولا',
    nameFa: 'آنگولا',
    dialCode: '+244',
    flag: '🇦🇴',
  },
  {
    code: 'MG',
    name: 'Madagascar',
    nameAr: 'مدغشقر',
    nameFa: 'ماداگاسکار',
    dialCode: '+261',
    flag: '🇲🇬',
  },
  {
    code: 'MU',
    name: 'Mauritius',
    nameAr: 'موريشيوس',
    nameFa: 'موریس',
    dialCode: '+230',
    flag: '🇲🇺',
  },
  {
    code: 'SC',
    name: 'Seychelles',
    nameAr: 'سيشل',
    nameFa: 'سیشل',
    dialCode: '+248',
    flag: '🇸🇨',
  },
  {
    code: 'RW',
    name: 'Rwanda',
    nameAr: 'رواندا',
    nameFa: 'رواندا',
    dialCode: '+250',
    flag: '🇷🇼',
  },
  {
    code: 'BI',
    name: 'Burundi',
    nameAr: 'بوروندي',
    nameFa: 'بوروندی',
    dialCode: '+257',
    flag: '🇧🇮',
  },
  {
    code: 'SZ',
    name: 'Eswatini',
    nameAr: 'إسواتيني',
    nameFa: 'اسواتینی',
    dialCode: '+268',
    flag: '🇸🇿',
  },
  {
    code: 'LS',
    name: 'Lesotho',
    nameAr: 'ليسوتو',
    nameFa: 'لسوتو',
    dialCode: '+266',
    flag: '🇱🇸',
  },
  {
    code: 'BW',
    name: 'Botswana',
    nameAr: 'بوتسوانا',
    nameFa: 'بوتسوانا',
    dialCode: '+267',
    flag: '🇧🇼',
  },
  {
    code: 'NA',
    name: 'Namibia',
    nameAr: 'ناميبيا',
    nameFa: 'نامیبیا',
    dialCode: '+264',
    flag: '🇳🇦',
  },
  {
    code: 'BR',
    name: 'Brazil',
    nameAr: 'البرازيل',
    nameFa: 'برزیل',
    dialCode: '+55',
    flag: '🇧🇷',
  },
  {
    code: 'AR',
    name: 'Argentina',
    nameAr: 'الأرجنتين',
    nameFa: 'آرژانتین',
    dialCode: '+54',
    flag: '🇦🇷',
  },
  {
    code: 'CL',
    name: 'Chile',
    nameAr: 'تشيلي',
    nameFa: 'شیلی',
    dialCode: '+56',
    flag: '🇨🇱',
  },
  {
    code: 'CO',
    name: 'Colombia',
    nameAr: 'كولومبيا',
    nameFa: 'کلمبیا',
    dialCode: '+57',
    flag: '🇨🇴',
  },
  {
    code: 'PE',
    name: 'Peru',
    nameAr: 'بيرو',
    nameFa: 'پرو',
    dialCode: '+51',
    flag: '🇵🇪',
  },
  {
    code: 'VE',
    name: 'Venezuela',
    nameAr: 'فنزويلا',
    nameFa: 'ونزوئلا',
    dialCode: '+58',
    flag: '🇻🇪',
  },
  {
    code: 'UY',
    name: 'Uruguay',
    nameAr: 'الأوروغواي',
    nameFa: 'اروگوئه',
    dialCode: '+598',
    flag: '🇺🇾',
  },
  {
    code: 'PY',
    name: 'Paraguay',
    nameAr: 'باراغواي',
    nameFa: 'پاراگوئه',
    dialCode: '+595',
    flag: '🇵🇾',
  },
  {
    code: 'BO',
    name: 'Bolivia',
    nameAr: 'بوليفيا',
    nameFa: 'بولیوی',
    dialCode: '+591',
    flag: '🇧🇴',
  },
  {
    code: 'EC',
    name: 'Ecuador',
    nameAr: 'الإكوادور',
    nameFa: 'اکوادور',
    dialCode: '+593',
    flag: '🇪🇨',
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    nameAr: 'كوستاريكا',
    nameFa: 'کاستاریکا',
    dialCode: '+506',
    flag: '🇨🇷',
  },
  {
    code: 'PA',
    name: 'Panama',
    nameAr: 'بنما',
    nameFa: 'پاناما',
    dialCode: '+507',
    flag: '🇵🇦',
  },
  {
    code: 'GT',
    name: 'Guatemala',
    nameAr: 'غواتيمالا',
    nameFa: 'گواتمالا',
    dialCode: '+502',
    flag: '🇬🇹',
  },
  {
    code: 'SV',
    name: 'El Salvador',
    nameAr: 'السلفادور',
    nameFa: 'السالوادور',
    dialCode: '+503',
    flag: '🇸🇻',
  },
  {
    code: 'HN',
    name: 'Honduras',
    nameAr: 'هندوراس',
    nameFa: 'هندوراس',
    dialCode: '+504',
    flag: '🇭🇳',
  },
  {
    code: 'NI',
    name: 'Nicaragua',
    nameAr: 'نيكاراغوا',
    nameFa: 'نیکاراگوئه',
    dialCode: '+505',
    flag: '🇳🇮',
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    nameAr: 'جمهورية الدومينيكان',
    nameFa: 'جمهوری دومینیکن',
    dialCode: '+1-809',
    flag: '🇩🇴',
  },
  {
    code: 'CU',
    name: 'Cuba',
    nameAr: 'كوبا',
    nameFa: 'کوبا',
    dialCode: '+53',
    flag: '🇨🇺',
  },
  {
    code: 'PR',
    name: 'Puerto Rico',
    nameAr: 'بورتوريكو',
    nameFa: 'پورتوریکو',
    dialCode: '+1-787',
    flag: '🇵🇷',
  },
  {
    code: 'JM',
    name: 'Jamaica',
    nameAr: 'جامايكا',
    nameFa: 'جامائیکا',
    dialCode: '+1-876',
    flag: '🇯🇲',
  },
  {
    code: 'TT',
    name: 'Trinidad and Tobago',
    nameAr: 'ترينيداد وتوباغو',
    nameFa: 'ترینیداد و توباگو',
    dialCode: '+1-868',
    flag: '🇹🇹',
  },
  {
    code: 'BS',
    name: 'Bahamas',
    nameAr: 'جزر البهاما',
    nameFa: 'باهاما',
    dialCode: '+1-242',
    flag: '🇧🇸',
  },
  {
    code: 'BB',
    name: 'Barbados',
    nameAr: 'باربادوس',
    nameFa: 'باربادوس',
    dialCode: '+1-246',
    flag: '🇧🇧',
  },
  {
    code: 'IL',
    name: 'Israel',
    nameAr: 'إسرائيل',
    nameFa: 'اسرائیل',
    dialCode: '+972',
    flag: '🇮🇱',
  },
  {
    code: 'PG',
    name: 'Papua New Guinea',
    nameAr: 'بابوا غينيا الجديدة',
    nameFa: 'پاپوا گینه نو',
    dialCode: '+675',
    flag: '🇵🇬',
  },
  {
    code: 'FJ',
    name: 'Fiji',
    nameAr: 'فيجي',
    nameFa: 'فیجی',
    dialCode: '+679',
    flag: '🇫🇯',
  },
  {
    code: 'SB',
    name: 'Solomon Islands',
    nameAr: 'جزر سليمان',
    nameFa: 'جزایر سلیمان',
    dialCode: '+677',
    flag: '🇸🇧',
  },
  {
    code: 'VU',
    name: 'Vanuatu',
    nameAr: 'فانواتو',
    nameFa: 'وانواتو',
    dialCode: '+678',
    flag: '🇻🇺',
  },
  {
    code: 'WS',
    name: 'Samoa',
    nameAr: 'ساموا',
    nameFa: 'ساموآ',
    dialCode: '+685',
    flag: '🇼🇸',
  },
  {
    code: 'TO',
    name: 'Tonga',
    nameAr: 'تونغا',
    nameFa: 'تونگا',
    dialCode: '+676',
    flag: '🇹🇴',
  },
  {
    code: 'KI',
    name: 'Kiribati',
    nameAr: 'كيريباتي',
    nameFa: 'کیریباتی',
    dialCode: '+686',
    flag: '🇰🇮',
  },
  {
    code: 'MH',
    name: 'Marshall Islands',
    nameAr: 'جزر مارشال',
    nameFa: 'جزایر مارشال',
    dialCode: '+692',
    flag: '🇲🇭',
  },
  {
    code: 'PW',
    name: 'Palau',
    nameAr: 'بالاو',
    nameFa: 'پالائو',
    dialCode: '+680',
    flag: '🇵🇼',
  },
  {
    code: 'FM',
    name: 'Micronesia',
    nameAr: 'ميكرونيزيا',
    nameFa: 'میکرونزی',
    dialCode: '+691',
    flag: '🇫🇲',
  },
  {
    code: 'NR',
    name: 'Nauru',
    nameAr: 'ناورو',
    nameFa: 'نائورو',
    dialCode: '+674',
    flag: '🇳🇷',
  },
  {
    code: 'TV',
    name: 'Tuvalu',
    nameAr: 'توفالو',
    nameFa: 'تووالو',
    dialCode: '+688',
    flag: '🇹🇻',
  },
  {
    code: 'CK',
    name: 'Cook Islands',
    nameAr: 'جزر كوك',
    nameFa: 'جزایر کوک',
    dialCode: '+682',
    flag: '🇨🇰',
  },
  {
    code: 'NU',
    name: 'Niue',
    nameAr: 'نييوي',
    nameFa: 'نیوئه',
    dialCode: '+683',
    flag: '🇳🇺',
  },
  {
    code: 'TK',
    name: 'Tokelau',
    nameAr: 'توكيلاو',
    nameFa: 'توکلائو',
    dialCode: '+690',
    flag: '🇹🇰',
  },
  {
    code: 'WF',
    name: 'Wallis and Futuna',
    nameAr: 'واليس وفوتونا',
    nameFa: 'والیس و فوتونا',
    dialCode: '+681',
    flag: '🇼🇫',
  },
  {
    code: 'PF',
    name: 'French Polynesia',
    nameAr: 'بولينزيا الفرنسية',
    nameFa: 'پلینزی فرانسه',
    dialCode: '+689',
    flag: '🇵🇫',
  },
  {
    code: 'NC',
    name: 'New Caledonia',
    nameAr: 'كاليدونيا الجديدة',
    nameFa: 'کالدونیای جدید',
    dialCode: '+687',
    flag: '🇳🇨',
  },
];

export const defaultCountry: Country = countries[0]!;
